version: '3.8'

services:
  db:
    image: postgres:13.3
    container_name: db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - TZ=Europe/Moscow

  server:
    build: ./server
    image: server
    container_name: server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - TZ=Europe/Moscow

  gateway:
    build: ./gateway
    image: gateway
    container_name: gateway
    ports:
      - "9090:9090"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - TZ=Europe/Moscow